services:
  db:
    image: postgres:16-bookworm
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      POSTGRES_DB: summitsync
    volumes:
      - pg-data:/var/lib/postgresql
    ports:
      - 5433:5432


volumes:
  pg-data:
